/// Flutter icons YoutubeShorts
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  YoutubeShorts
///      fonts:
///       - asset: fonts/YoutubeShorts.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class YoutubeShorts {
  YoutubeShorts._();

  static const _kFontFam = 'YoutubeShorts';
  static const String? _kFontPkg = null;

  static const IconData shorts = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
